version: '3.8'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "8080:80"
    volumes:
      - ./docs:/app/docs
    environment:
      - NODE_ENV=production
