name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run code quality checks
        run: |
          npx tsc --noEmit
          npx eslint . --ext .ts,.tsx,.js,.jsx --report-unused-disable-directives --max-warnings 0
          npx prettier --check .
          
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
          
      - name: Build application
        run: npm run build
        
      - name: Deploy to Replit
        if: success()
        run: |
          echo "✅ Build successful! Ready for deployment."
          echo "To deploy this application:"
          echo "1. Push these changes to your main branch"
          echo "2. In Replit, click the Deploy button"
          echo "3. Configure your environment variables"
          echo "4. Your app will be available at your-app.replit.app"