name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build development image
        run: docker build -f Dockerfile.dev -t jobblaster:dev .
        
      - name: Build production image
        run: docker build -f Dockerfile -t jobblaster:prod .
        
      - name: Test development container
        run: |
          docker run --rm -d --name jobblaster-test -p 3000:3000 jobblaster:dev
          sleep 10
          curl -f http://localhost:3000/api/health || exit 1
          docker stop jobblaster-test
          
      - name: Test production container
        run: |
          docker run --rm -d --name jobblaster-prod-test -p 3001:3000 jobblaster:prod
          sleep 15
          curl -f http://localhost:3001/api/health || exit 1
          docker stop jobblaster-prod-test
          
      - name: Run security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'jobblaster:prod'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'